services:
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    environment:
      ENCRYPTION_SECRET: "${ENCRYPTION_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXT_PUBLIC_VIEWER_URL: "${NEXT_PUBLIC_VIEWER_URL}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      SMTP_HOST: "${SMTP_HOST}"
      NEXT_PUBLIC_SMTP_FROM: "${NEXT_PUBLIC_SMTP_FROM}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      SMTP_AUTH_DISABLED: "${SMTP_AUTH_DISABLED}"
      DEFAULT_WORKSPACE_PLAN: "${DEFAULT_WORKSPACE_PLAN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      DISABLE_SIGNUP: "${DISABLE_SIGNUP}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_PORT: "${S3_PORT}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_SSL: "${S3_SSL}"
    ports:
      - "${BUILDER_PORT:-8083}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  # typebot-landing-page:
  #   build:
  #     context: .
  #     args:
  #       - SCOPE=landing-page
  #   restart: always
  #   environment:
  #     LANDING_PAGE_URL: "${LANDING_PAGE_URL}"
  #   ports:
  #     - "8085:3000"

  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    environment:
      ENCRYPTION_SECRET: "${ENCRYPTION_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXT_PUBLIC_VIEWER_URL: "${NEXT_PUBLIC_VIEWER_URL}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      SMTP_HOST: "${SMTP_HOST}"
      NEXT_PUBLIC_SMTP_FROM: "${NEXT_PUBLIC_SMTP_FROM}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      SMTP_AUTH_DISABLED: "${SMTP_AUTH_DISABLED}"
      DEFAULT_WORKSPACE_PLAN: "${DEFAULT_WORKSPACE_PLAN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      DISABLE_SIGNUP: "${DISABLE_SIGNUP}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_PORT: "${S3_PORT}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_SSL: "${S3_SSL}"
    ports:
      - "${VIEWER_PORT:-8084}:3000"
