volumes:
  db-data:

services:
  typebot-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: typebot
      POSTGRES_DB: typebot
      POSTGRES_PASSWORD: typebot
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    environment:
      ENCRYPTION_SECRET: "${ENCRYPTION_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXT_PUBLIC_VIEWER_URL: "${NEXT_PUBLIC_VIEWER_URL}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      SMTP_HOST: "${SMTP_HOST}"
      NEXT_PUBLIC_SMTP_FROM: "${NEXT_PUBLIC_SMTP_FROM}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      SMTP_AUTH_DISABLED: "${SMTP_AUTH_DISABLED}"
      DEFAULT_WORKSPACE_PLAN: "${DEFAULT_WORKSPACE_PLAN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      DISABLE_SIGNUP: "${DISABLE_SIGNUP}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_PORT: "${S3_PORT}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_SSL: "${S3_SSL}"
      S3_PUBLIC_CUSTOM_DOMAIN: "${S3_PUBLIC_CUSTOM_DOMAIN}"
    ports:
      - "${BUILDER_PORT:-8083}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    environment:
      ENCRYPTION_SECRET: "${ENCRYPTION_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXT_PUBLIC_VIEWER_URL: "${NEXT_PUBLIC_VIEWER_URL}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      SMTP_HOST: "${SMTP_HOST}"
      NEXT_PUBLIC_SMTP_FROM: "${NEXT_PUBLIC_SMTP_FROM}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      SMTP_AUTH_DISABLED: "${SMTP_AUTH_DISABLED}"
      DEFAULT_WORKSPACE_PLAN: "${DEFAULT_WORKSPACE_PLAN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      DISABLE_SIGNUP: "${DISABLE_SIGNUP}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_PORT: "${S3_PORT}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_SSL: "${S3_SSL}"
      S3_PUBLIC_CUSTOM_DOMAIN: "${S3_PUBLIC_CUSTOM_DOMAIN}"
    ports:
      - "${VIEWER_PORT:-8084}:3000"
